language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - npm install -g firebase-tools
script:
  - npm test
after_success:
  - npm run build
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - develop