language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - yarn install
script:
  - yarn test
after_success:
  - yarn run build
  - firebase deploy -m "Travis deploy" --non-interactive --token "1/bxM5zVElqlWm1DX0tmuKe0hz9yV_OlcaZmtOpeidYho"
branches:
  only:
    - develop
